name: BDD with Gauge

on:
  push

jobs:
  gauge-test:
   name: Run Gauge tests
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
     - name: Browser setting
       run: sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
     - name: Install dependencies
       run: npm install -g @getgauge/cli
     - name: Check Gauge Version
       run: gauge version
     - name: Setup Gaguse
       run: npm ci & gauge install
       working-directory: ./home/bdd/gauge-tests
     - name: Run Tests
       run: gauge run
       working-directory: ./home/bdd/gauge-tests